# Generated by Django 5.2.1 on 2026-01-14 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeoApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
                ('domain_name', models.URLField(max_length=255)),
                ('competitor1_brand_name', models.CharField(max_length=255)),
                ('competitor1_domain_name', models.URLField(max_length=255)),
                ('competitor2_brand_name', models.CharField(max_length=255)),
                ('competitor2_domain_name', models.URLField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Brand Profile',
                'verbose_name_plural': 'Brand Profiles',
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
