# Generated by Django 5.2.1 on 2026-01-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeoApp', '0002_brandprofile_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='is_brand_created',
            field=models.BooleanField(default=False),
        ),
    ]
