# Generated by Django 5.2.1 on 2026-01-16 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeoApp', '0003_brandprofile_is_brand_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
                ('domain_name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='aeoApp.brandprofile')),
            ],
        ),
    ]
