# Generated by Django 5.2.1 on 2026-01-16 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeoApp', '0004_competitors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandprofile',
            name='competitor1_brand_name',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='competitor1_domain_name',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='competitor2_brand_name',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='competitor2_domain_name',
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='url',
            field=models.URLField(default='https://www.google.com/', max_length=255),
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='domain_name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='SecondaryBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
                ('domain_name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_brands', to='aeoApp.brandprofile')),
            ],
        ),
    ]
