# Generated by Django 5.2.1 on 2026-01-24 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeoApp', '0005_remove_brandprofile_competitor1_brand_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('ai_response', models.TextField()),
                ('user_brand_mentioned', models.BooleanField(default=False)),
                ('competitor_mentioned', models.BooleanField(default=False)),
                ('mentioned_brands', models.JSONField(default=list)),
                ('mentioned_domains', models.JSONField(default=list)),
                ('source_type', models.CharField(choices=[('LLM', 'LLM Knowledge'), ('SEARCH', 'Search AI')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_history', to='aeoApp.brandprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrandMentionMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
                ('total_mentions', models.PositiveIntegerField(default=0)),
                ('last_mentioned_at', models.DateTimeField(blank=True, null=True)),
                ('brand_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mention_metrics', to='aeoApp.brandprofile')),
            ],
            options={
                'unique_together': {('brand_profile', 'brand_name')},
            },
        ),
        migrations.CreateModel(
            name='BrandMentionTimeseries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('mentions', models.PositiveIntegerField(default=0)),
                ('brand_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeseries', to='aeoApp.brandprofile')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('brand_profile', 'brand_name', 'date')},
            },
        ),
    ]
