"""
Django settings for aeo project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secrt!
SECRET_KEY = 'django-insecure-m(2iri=2vc-d$+*w4o5w6fkd#q#ssm_2pg=$d4u@qps#u^y7#%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['malangcode.pythonanywhere.com', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'aeoApp',
    'rest_framework',
    'corsheaders',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
]

SITE_ID = 1

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'aeoApp.authentication.CookieJWTAuthentication',  # ✅ Custom authentication class
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # ✅ Default permission
    ],
}

REST_USE_JWT = True

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_COOKIE': 'access_token',  # ✅ custom cookie name
    'AUTH_COOKIE_REFRESH': 'refresh_token',  # ✅ refresh cookie name
    'AUTH_COOKIE_HTTP_ONLY': True,
    'AUTH_COOKIE_SECURE': True,  # ✅ Set to True in production with HTTPS
    'AUTH_COOKIE_SAMESITE': 'none',
}



# ✅ ENABLE username again if you want it entered manually
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'   # Still using email to login
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'none'

# ✅ Accept both email and username during signup
ACCOUNT_SIGNUP_FIELDS = {
    'email': {'required': True},
    'username': {'required': True},
}

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
    },
    "github": {
        "SCOPE": [
            "read:user",
            "user:email",
        ],
        # You can add AUTH_PARAMS here if needed, e.g. "allow_signup": "true"
    },
}

SOCIALACCOUNT_ADAPTER = 'aeoApp.adapters.CustomSocialAccountAdapter'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'aeo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aeo.wsgi.application'


CORS_ALLOW_CREDENTIALS = True

# Allow your frontend origin (RECOMMENDED for dev)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://smartcoderrahis.pythonanywhere.com",
    "https://dev-rumble-nextapp.vercel.app",
    "https://aeo-frontend.vercel.app",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "https://smartcoderrahis.pythonanywhere.com",
    "https://dev-rumble-nextapp.vercel.app",
    "https://aeo-frontend.vercel.app",
]


SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"  # or "same-origin-allow-popups"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',          # default
    'allauth.account.auth_backends.AuthenticationBackend',  # ≤ required for email login
)




# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kathmandu'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # for custom static files in development
STATIC_ROOT = BASE_DIR / 'staticfiles'    # for collectstatic (e.g., for production)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'  # where uploaded files will be saved



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# # Cokiee settings  for production
SESSION_COOKIE_SAMESITE = "None"       # ❗ Required for cross-domain
SESSION_COOKIE_SECURE = True           # ❗ Required with SameSite=None
CSRF_COOKIE_SAMESITE = "None"          # ❗ Required if CSRF cookie used
CSRF_COOKIE_SECURE = True

# ✅ Cookie settings for local development (localhost)
# ✅ Best settings for localhost (http://127.0.0.1 or http://localhost)
# SESSION_COOKIE_SECURE = False
# SESSION_COOKIE_SAMESITE = "Lax"        # ✅ or "Strict"

# CSRF_COOKIE_SECURE = False
# CSRF_COOKIE_SAMESITE = "Lax"           # ✅ or "Strict"

# CSRF_COOKIE_HTTPONLY = False
# CSRF_USE_SESSIONS = False              # Only True if storing token in session